const callFunctions = [
  "name",
  "symbol",
  "granularity",
  "isControllable",
  "isIssuable",
  "balanceOf",
  "allowance",
  "totalPartitions",
  "totalSupply",
  "totalSupplyByPartition",
  "partitionsOf",
  "balanceOfByPartition",
  "allowanceByPartition",
  "isOperator",
  "isOperatorForPartition",
  "controllers",
  "controllersByPartition",
  "isMinter",
];

const sendFunctions = [
  "authorizeOperator",
  "revokeOperator",
  "authorizeOperatorByPartition",
  "revokeOperatorByPartition",
  "approve",
  "approveByPartition",
  "transfer",
  "transferWithData",
  "transferFrom",
  "transferFromWithData",
  "transferByPartition",
  "operatorTransferByPartition",
  "redeem",
  "redeemFrom",
  "redeemByPartition",
  "operatorRedeemByPartition",
];

module.exports = { callFunctions, sendFunctions };
